name = "ip-lookup"
main = "src/index.ts"
compatibility_date = "2022-11-05"

workers_dev = false
route = { pattern = "ip.rootnet.in/*", zone_name = "rootnet.in" }

kv_namespaces = [
	 { binding = "IP2NETWORK", id = "16293b30e01143649f10a2ef63ca72aa", preview_id = "16293b30e01143649f10a2ef63ca72aa" }
]
